spring:
  application:
    name: personal-expenses-tracker
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://db.your-supabase-url.com:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:your-password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyForJWTTokenGenerationInPersonalExpensesTrackerApplication2024}
    expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method